spring:
  application:
    name: sistema-chamados-ti

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
app:
  admin:
    email: ${ADMIN_EMAIL:admin@chamados.local}
    senha: ${ADMIN_SENHA:Admin@12345}