spring:
  application:
    name: sistema-chamados-ti
  datasource:
    url: jdbc:postgresql://localhost:5432/chamadosbd
    username: postgres
    password: post2001
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
